services:
  - type: web
    name: contel-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contel-db
          property: connectionString
      - key: ADMIN_PASS
        value: contel@2024
      - key: SESSION_SECRET
        generateValue: true
      - key: HTTPS
        value: "true"

databases:
  - name: contel-db
    plan: free
